### ISSUE TITLE
More fine-grained customization of the OCI image reference

### ISSUE THREAD

**Issue by Djaytan** [Djaytan/helm-papermc-server#14]
Actually, the `container.image` property is a `string` one: [link](https://github.com/Djaytan/helm-papermc-server/blob/main/src/values.schema.json#L22-L25).

The goal here is to split convert it to `object` and expose three sub-properties:
* `registry`: hostname server from where the OCI image must be pulled (default value: `docker.io`)
* `name`: the image name (default value: `djaytan/papermc-server`)
* `tag`: the image tag (default value: `latest`)
* `digest`: the checksum for integrity check (default value: _none_)

This way, as a user, I can just override the tag without bothering about anything else:
```yaml
container:
  image:
    tag: '1.21.4-v2.11'
    digest: 'sha256:7136fadbae3f4acf8c4f470d047516af0fda4f3298de85aa14f7b9f8347019fe'
```

Alternatively, or complementary, I can as well create my own custom OCI image based on the Djaytan's one while still using this Helm chart:
```yaml
container:
  image:
    registry: ghcr.io
    name: my-org/my-repo
    tag: latest
```

Or I may need to override specifically the registry in order to rely on a mirror to avoid facing Docker Hub rate limits:
```yaml
container:
  image:
    registry: my-mirror.io
```
